# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[(b'abnf', b'ABNF'), (b'ada', b'Ada'), (b'ahk', b'autohotkey'), (b'antlr-csharp', b'ANTLR With C# Target'), (b'antlr-objc', b'ANTLR With ObjectiveC Target'), (b'as', b'ActionScript'), (b'aspx-cs', b'aspx-cs'), (b'aspx-vb', b'aspx-vb'), (b'at', b'AmbientTalk'), (b'autoit', b'AutoIt'), (b'bash', b'Bash'), (b'bbcode', b'BBCode'), (b'bc', b'BC'), (b'brainfuck', b'Brainfuck'), (b'bro', b'Bro'), (b'cadl', b'cADL'), (b'cbmbas', b'CBM BASIC V2'), (b'ceylon', b'Ceylon'), (b'cfm', b'Coldfusion HTML'), (b'cfs', b'cfstatement'), (b'cirru', b'Cirru'), (b'cmake', b'CMake'), (b'coffee-script', b'CoffeeScript'), (b'cpp', b'C++'), (b'csound', b'Csound Orchestra'), (b'css+django', b'CSS+Django/Jinja'), (b'css+erb', b'CSS+Ruby'), (b'css+genshitext', b'CSS+Genshi Text'), (b'css+mako', b'CSS+Mako'), (b'css+mozpreproc', b'CSS+mozpreproc'), (b'css+php', b'CSS+PHP'), (b'css+smarty', b'CSS+Smarty'), (b'cucumber', b'Gherkin'), (b'dylan-console', b'Dylan session'), (b'elm', b'Elm'), (b'fan', b'Fantom'), (b'fancy', b'Fancy'), (b'fish', b'Fish'), (b'genshitext', b'Genshi Text'), (b'golo', b'Golo'), (b'html+evoque', b'HTML+Evoque'), (b'html+genshi', b'HTML+Genshi'), (b'idl', b'IDL'), (b'idris', b'Idris'), (b'inform6', b'Inform 6'), (b'io', b'Io'), (b'j', b'J'), (b'jags', b'JAGS'), (b'java', b'Java'), (b'jcl', b'JCL'), (b'js+myghty', b'JavaScript+Myghty'), (b'json', b'JSON'), (b'julia', b'Julia'), (b'kconfig', b'Kconfig'), (b'lagda', b'Literate Agda'), (b'less', b'LessCss'), (b'llvm', b'LLVM'), (b'mako', b'Mako'), (b'maql', b'MAQL'), (b'minid', b'MiniD'), (b'mozpercentpreproc', b'mozpercentpreproc'), (b'mupad', b'MuPAD'), (b'mysql', b'MySQL'), (b'nasm', b'NASM'), (b'nemerle', b'Nemerle'), (b'nimrod', b'Nimrod'), (b'nit', b'Nit'), (b'numpy', b'NumPy'), (b'objective-j', b'Objective-J'), (b'odin', b'ODIN'), (b'openedge', b'OpenEdge ABL'), (b'pike', b'Pike'), (b'pkgconfig', b'PkgConfig'), (b'plpgsql', b'PL/pgSQL'), (b'powershell', b'PowerShell'), (b'py3tb', b'Python 3.0 Traceback'), (b'pycon', b'Python console session'), (b'pytb', b'Python Traceback'), (b'ragel', b'Ragel'), (b'ragel-c', b'Ragel in C Host'), (b'ragel-ruby', b'Ragel in Ruby Host'), (b'roboconf-instances', b'Roboconf Instances'), (b'rsl', b'RSL'), (b'sass', b'Sass'), (b'sc', b'SuperCollider'), (b'scaml', b'Scaml'), (b'smalltalk', b'Smalltalk'), (b'spec', b'RPMSpec'), (b'squidconf', b'SquidConf'), (b'ssp', b'Scalate Server Page'), (b'tcshcon', b'Tcsh Session'), (b'terminfo', b'Terminfo'), (b'ts', b'TypeScript'), (b'urbiscript', b'UrbiScript'), (b'vim', b'VimL'), (b'xml+erb', b'XML+Ruby'), (b'xml+evoque', b'XML+Evoque'), (b'xml+mako', b'XML+Mako'), (b'xml+smarty', b'XML+Smarty'), (b'xtend', b'Xtend'), (b'xul+mozpreproc', b'XUL+mozpreproc')], default='python', max_length=100)),
                ('style', models.CharField(choices=[(b'algol', b'algol'), (b'algol_nu', b'algol_nu'), (b'autumn', b'autumn'), (b'borland', b'borland'), (b'bw', b'bw'), (b'colorful', b'colorful'), (b'default', b'default'), (b'emacs', b'emacs'), (b'friendly', b'friendly'), (b'fruity', b'fruity'), (b'igor', b'igor'), (b'lovelace', b'lovelace'), (b'manni', b'manni'), (b'monokai', b'monokai'), (b'murphy', b'murphy'), (b'native', b'native'), (b'paraiso-dark', b'paraiso-dark'), (b'paraiso-light', b'paraiso-light'), (b'pastie', b'pastie'), (b'perldoc', b'perldoc'), (b'rrt', b'rrt'), (b'tango', b'tango'), (b'trac', b'trac'), (b'vim', b'vim'), (b'vs', b'vs'), (b'xcode', b'xcode')], default='friendly', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
